# Generated by Django 5.1.7 on 2025-03-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NguoiDung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_dang_nhap", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("mat_khau", models.CharField(max_length=255)),
                (
                    "vai_tro",
                    models.CharField(
                        choices=[
                            ("NguoiDung", "Người Dùng"),
                            ("QuanTriVien", "Quản Trị Viên"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=100)),
                ("the_loai", models.CharField(max_length=50)),
                ("thoi_luong", models.IntegerField()),
                ("ngay_phat_hanh", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diem_danh_gia", models.PositiveSmallIntegerField()),
                ("binh_luan", models.TextField()),
                ("ngay_danh_gia", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinego.nguoidung",
                    ),
                ),
                (
                    "phim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinego.phim"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuanTriVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinego.nguoidung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian_chieu", models.DateTimeField()),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinego.nguoidung",
                    ),
                ),
                (
                    "phim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinego.phim"
                    ),
                ),
            ],
        ),
    ]
