# Generated by Django 5.1.7 on 2025-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinego", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phim",
            name="anh_phim",
            field=models.ImageField(default="", upload_to="phim/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phim",
            name="dao_dien",
            field=models.CharField(default="Natra.jpg", max_length=100),
            preserve_default=False,
        ),
    ]
