# Generated by Django 5.1.7 on 2025-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinego", "0003_chinhanh"),
    ]

    operations = [
        migrations.AddField(
            model_name="phim",
            name="coming_soon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="phim",
            name="is_now_showing",
            field=models.BooleanField(default=False),
        ),
    ]
