# Generated by Django 5.1.7 on 2025-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinego", "0004_phim_coming_soon_phim_is_now_showing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nguoidung",
            name="mat_khau",
        ),
        migrations.RemoveField(
            model_name="nguoidung",
            name="ten_dang_nhap",
        ),
        migrations.RemoveField(
            model_name="nguoidung",
            name="vai_tro",
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="ho_ten",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="so_dien_thoai",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="nguoidung",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
