# Generated by Django 5.1.7 on 2025-04-01 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chi_nhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('duong_dan_anh', models.URLField(blank=True, max_length=1000, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='phim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('dao_dien', models.CharField(max_length=255)),
                ('dien_vien', models.TextField()),
                ('the_loai', models.CharField(max_length=255)),
                ('ngon_ngu', models.CharField(max_length=100)),
                ('danh_gia', models.CharField(max_length=100)),
                ('ngay_phat_hanh', models.DateField()),
                ('trailer', models.URLField(blank=True, max_length=1000, null=True)),
                ('mo_ta_ngan', models.TextField()),
                ('mo_ta_dai', models.TextField()),
                ('dang_chieu', models.BooleanField(default=False)),
                ('duong_dan_anh', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('suc_chua', models.IntegerField()),
                ('tong_dien_tich', models.FloatField()),
                ('duong_dan_anh', models.URLField(blank=True, max_length=1000, null=True)),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.chi_nhanh')),
            ],
        ),
        migrations.CreateModel(
            name='ghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('loai_ghe', models.IntegerField()),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.phong')),
            ],
        ),
    ]
