# Generated by Django 5.1.7 on 2025-04-01 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bai_viet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('tom_tat', models.TextField()),
                ('anh_chinh', models.URLField(max_length=255)),
                ('trang_thai', models.IntegerField()),
                ('loai', models.IntegerField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='nguoi_dung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mat_khau', models.CharField(max_length=100)),
                ('ten_dang_nhap', models.CharField(max_length=15, unique=True)),
                ('duong_dan_anh', models.URLField(blank=True, max_length=100, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vai_tro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='lich_chieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('gia', models.FloatField()),
                ('ngay_bat_dau', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.chi_nhanh')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.phim')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.phong')),
            ],
        ),
        migrations.CreateModel(
            name='hoa_don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.nguoi_dung')),
            ],
        ),
        migrations.CreateModel(
            name='nguoi_dung_vai_tro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.nguoi_dung')),
                ('vai_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.vai_tro')),
            ],
        ),
        migrations.CreateModel(
            name='ve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('ghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.ghe')),
                ('lich_chieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.lich_chieu')),
            ],
        ),
    ]
