# Generated by Django 5.1.7 on 2025-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_thanh_toan_ngay_cap_nhat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanh_toan',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thanh_toan',
            name='trangthai',
            field=models.IntegerField(default=0),
        ),
    ]
