# Generated by Django 5.1.7 on 2025-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_thanh_toan_ngay_cap_nhat_alter_thanh_toan_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanh_toan',
            name='ve',
            field=models.JSONField(),
        ),
    ]
