# Generated by Django 5.1.7 on 2025-04-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_thanh_toan_ve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lich_chieu',
            name='gia',
        ),
    ]
