# Generated by Django 5.1.7 on 2025-04-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_thanh_toan_tong_gia_ve'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.nguoi_dung')),
            ],
        ),
    ]
