# Generated by Django 5.1.7 on 2025-04-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanh_toan',
            name='soluong',
        ),
        migrations.AlterField(
            model_name='thanh_toan',
            name='ngay_cap_nhat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thanh_toan',
            name='tong_gia_ve',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
