# Generated by Django 5.1.7 on 2025-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0011_phim_gia_ve"),
    ]

    operations = [
        migrations.AddField(
            model_name="ve",
            name="trang_thai",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="ve",
            unique_together={("lich_chieu", "ghe")},
        ),
    ]
