# Generated by Django 5.1.7 on 2025-04-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0012_ve_trang_thai_alter_ve_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ve",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="ve",
            name="trang_thai",
        ),
    ]
