# Generated by Django 5.1.7 on 2025-04-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0013_alter_ve_unique_together_remove_ve_trang_thai"),
    ]

    operations = [
        migrations.AddField(
            model_name="phim",
            name="banner",
            field=models.URLField(
                default="https://example.com/no_banner.jpg", max_length=255
            ),
        ),
    ]
